# Generated by Django 4.2.7 on 2023-11-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0002_remove_ticketing_time_ticketing_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketing',
            name='finish_time',
        ),
        migrations.RemoveField(
            model_name='ticketing',
            name='start_time',
        ),
        migrations.AddField(
            model_name='ticketing',
            name='movie_times',
            field=models.CharField(default='120', max_length=20, verbose_name='상영 시간'),
        ),
        migrations.AlterField(
            model_name='ticketing',
            name='date',
            field=models.DateTimeField(verbose_name='날짜'),
        ),
    ]
