# Generated by Django 4.2.3 on 2023-11-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0003_remove_ticketing_finish_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketing',
            name='movie_times',
            field=models.CharField(max_length=20, verbose_name='상영 시간'),
        ),
    ]
