# Generated by Django 4.2.3 on 2023-11-25 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0004_alter_ticketing_movie_times'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ticketing',
            table='ticketing',
        ),
    ]
