# Generated by Django 4.2.3 on 2023-11-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0005_alter_ticketing_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketing',
            name='movie_times',
            field=models.CharField(default=0, max_length=20, verbose_name='상영 시간'),
        ),
        migrations.AlterField(
            model_name='ticketing',
            name='seat_all',
            field=models.JSONField(default={'0': 1}),
        ),
    ]
