# Generated by Django 4.2.7 on 2023-11-26 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0007_area_alter_ticketing_seat_all'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='theaters',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(choices=[('서울', 'Seoul'), ('경기', 'Gyeonggi'), ('인천', 'Incheon'), ('강원', 'Gangwon'), ('대전/충청', 'Daejeon/Chungcheong'), ('대구', 'Daegu'), ('부산/울산', 'Busan/Ulsan'), ('경상', 'Gyeongsang'), ('광주/전라/제주', 'Gwangju/Jeolla/Jeju')], max_length=100),
        ),
        migrations.AlterField(
            model_name='ticketing',
            name='seat_all',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='Theather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.area')),
            ],
        ),
    ]
