# Generated by Django 4.2.7 on 2023-11-26 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0010_alter_area_options_alter_theater_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketing',
            name='theater',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ticketing.theater'),
            preserve_default=False,
        ),
    ]
