# Generated by Django 4.2.7 on 2023-11-26 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0012_alter_ticketing_theater'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketing',
            name='theater',
        ),
    ]
