# Generated by Django 4.2.7 on 2023-11-26 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0013_remove_ticketing_theater'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketing',
            name='theater',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ticketing.theater'),
            preserve_default=False,
        ),
    ]
