# Generated by Django 4.2.1 on 2023-11-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0014_ticketing_theater'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketing',
            name='user',
            field=models.BooleanField(default=False),
        ),
    ]
