# Generated by Django 4.2.1 on 2023-11-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0017_alter_ticketing_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketing',
            name='user',
            field=models.JSONField(default=['']),
        ),
    ]
