# Generated by Django 4.2.1 on 2023-11-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_user_ticket_options_user_ticket_cinema_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_ticket',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
