# Generated by Django 4.2.7 on 2023-11-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='times',
            field=models.CharField(default='120', max_length=20, verbose_name='상영시간'),
        ),
    ]
